//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haber()
        {
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int Id { get; set; }
        public Nullable<int> YazarId { get; set; }
        public string Icerik { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Onay { get; set; }
        public string Baslik { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
