//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Id { get; set; }
        public Nullable<int> Yazar { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Haber { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        public virtual Haber Haber1 { get; set; }
    }
}
